development:
  cloud_name: apostrophe
  api_key: '967794695543552'
  api_secret: t97aeet1KMqp3AlZNF0_N3oE4ws
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: apostrophe
  api_key: '967794695543552'
  api_secret: t97aeet1KMqp3AlZNF0_N3oE4ws
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: apostrophe
  api_key: '967794695543552'
  api_secret: t97aeet1KMqp3AlZNF0_N3oE4ws
  enhance_image_tag: true
  static_image_support: false
